#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

cd geeksbot_web

python manage.py collectstatic --noinput
python manage.py makemigrations --noinput
python manage.py migrate

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
